CREATE TABLE MO_WAREHOUSE.IEX_GTAM (
	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	TIME_STAMP DATE,
	col_attributes VARCHAR2(250),
    CONTRACT_TYPE VARCHAR2(250),
    instrument_name VARCHAR2(250),
	data_VALUE NUMBER(25,4),
    UNIQUE(time_stamp,col_attributes,instrument_name,data_value)
);